# Generated by Django 5.0.4 on 2024-04-30 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ConstructionElement",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("nom", models.CharField(max_length=255)),
                ("unite", models.CharField(max_length=100)),
                ("impactUnitaireRechauffementClimatique", models.JSONField()),
                ("dureeVieTypique", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Usage",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("label", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Zone",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("nom", models.CharField(max_length=255)),
                ("surface", models.FloatField()),
                ("usage", models.IntegerField()),
                ("constructionElements", models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name="Batiment",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("nom", models.CharField(max_length=255)),
                ("surface", models.FloatField(null=True)),
                ("zoneIds", models.JSONField()),
                ("periodeDeReference", models.IntegerField()),
                (
                    "usage",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="DRF_App.usage",
                    ),
                ),
            ],
        ),
    ]
